### ISSUE TITLE
Blank Settings Page

### ISSUE THREAD

**Issue by a-rodriguez** [notify-events/homebridge#2] opened 2022-08-03 17:35 UTC
Just updated to the new version 1.3.0 and get a blank screen when I click on settings.

<img width="878" alt="Screen Shot 2022-08-03 at 1 32 46 PM" src="https://user-images.githubusercontent.com/17552897/182672547-31b29fad-6c09-4d3d-8fc9-a67a51c22b3a.png">

Browser is Safari. Worked fine prior to the update to 1.3.0.

**Comment by matrozov** [comment] 2022-08-03 17:37
Hello, could you please attach your current config file (only Notify.Events platform section)?

**Comment by a-rodriguez** [comment] 2022-08-03 17:43
Let me know if this helps or you need more details. I XXXed out the real token.

`        {
            "platform": "NotifyEvents",
            "action": {
                "enabled": false,
                "listen": "0.0.0.0",
                "port": 53535,
                "host": "",
                "path": "/"
            },
            "channels": [
                {
                    "title": "HB-Test",
                    "token": "XXXXXXX",
                    "messages": [
                        {
                            "name": "NotifyDotEvents",
                            "title": "NDE Test",
                            "text": "This is a test",
                            "priority": "normal",
                            "level": "info",
                            "actions": []
                        }
                    ]
                }
            ]
        }
    ],`

**Comment by matrozov** [comment] 2022-08-03 17:48
I can't reproduce the error with your config. Can you provide the version of Homebridge and the Homebridge UI plugin?

Also, could you look at the error in the browser console? (For Chrome browser: press F12 and in the window that opens, copy the error (highlighted in red) from the "console" tab)

Thanks for your help.

**Comment by KJTamas** [comment] 2022-08-04 09:41
I have same issue. 
Homebirdge UI: 4.50.0
Notify.events: 1.3.0

**Comment by matrozov** [comment] 2022-08-04 09:59
> I have same issue. Homebirdge UI: 4.50.0 Notify.events: 1.3.0

Could you look at the error in the browser console? (For Chrome browser: press F12 and in the window that opens, copy the error (highlighted in red) from the "console" tab)

**Comment by matrozov** [comment] 2022-08-04 10:00
Can you check. If you add empty images/files sections according to the documentation to the message entity, will the problem go away?

**Comment by KJTamas** [comment] 2022-08-04 10:13
I am using on iPad pro, and Safari. I tried on iPhone, and works fine. 🤷🏻‍♂️ I download to iPad the Chrome, and there is working fine. Really don’t understand….

**Comment by matrozov** [comment] 2022-08-04 10:15
> I am using on iPad pro, and Safari. I tried on iPhone, and works fine. 🤷🏻‍♂️ I download to iPad the Chrome, and there is working fine. Really don’t understand….

Thank you. We will try to find a way to reproduce this.

@a-rodriguez, what device and browser are you getting the error on? Thank you.

**Comment by matrozov** [comment] 2022-08-04 11:02
> I am using on iPad pro, and Safari. I tried on iPhone, and works fine. 🤷🏻‍♂️ I download to iPad the Chrome, and there is working fine. Really don’t understand….

@KJTamas I have an idea. Can you try resetting the browser cache on the iPad where is the problem?

**Comment by a-rodriguez** [comment] 2022-08-04 11:10
I am on a M1 MacBook, using Safari Version 15.6 (17613.3.9.1.5). My Homebridge is running on a Raspberry Pi 4, Homebridge v1.5.0, Node v16.16.0, homebridge-config-ui-x v4.50.0. Let me know if you need any more details.

**Comment by matrozov** [comment] 2022-08-04 12:29
> I am on a M1 MacBook, using Safari Version 15.6 (17613.3.9.1.5). My Homebridge is running on a Raspberry Pi 4, Homebridge v1.5.0, Node v16.16.0, homebridge-config-ui-x v4.50.0. Let me know if you need any more details.

Please try resetting your browser cache.

**Comment by a-rodriguez** [comment] 2022-08-04 13:34
> > I am on a M1 MacBook, using Safari Version 15.6 (17613.3.9.1.5). My Homebridge is running on a Raspberry Pi 4, Homebridge v1.5.0, Node v16.16.0, homebridge-config-ui-x v4.50.0. Let me know if you need any more details.
> 
> Please try resetting your browser cache.

That worked, thank you!

**Comment by matrozov** [comment] 2022-08-04 13:36
> > > I am on a M1 MacBook, using Safari Version 15.6 (17613.3.9.1.5). My Homebridge is running on a Raspberry Pi 4, Homebridge v1.5.0, Node v16.16.0, homebridge-config-ui-x v4.50.0. Let me know if you need any more details.
> > 
> > 
> > Please try resetting your browser cache.
> 
> That worked, thank you!

Thanks for confirming the cause of the problem. We will fix and release the release so that the cache does not break the update.

**Comment by KJTamas** [comment] 2022-08-04 16:04
I can confirm, that resetting cache resolve the issue… Thank You!!

**Comment by matrozov** [comment] 2022-08-04 20:18
Fixed in 1.3.1

**Closed as completed by matrozov** 2022-08-04 20:18 UTC
Labels: bug
